PracticalTest/Controllers/MarkController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PracticalTest.Models;
using PracticalTest.Service.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PracticalTest.Controllers
{
    [Authorize]
    [Route("[controller]/[action]")]
    public class MarkController : Controller
    {
        private readonly IMarkService markService;

        public MarkController(IMarkService markService)
        {
            this.markService = markService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AddMarks()
        {
            return View();
        }

        //[HttpPost]
        //public async Task<IActionResult> SaveMarks([FromBody]Mark article)
        //{


        //    return new JsonResult("");
        //}

        [HttpPost]
        public async Task<IActionResult> SaveMarks([FromBody] Mark mark)
        {
            var model = new Domain.Models.Mark
            {
                Marks = mark.Marks,
                TeacherSubjectId = mark.TeacherSubjectId,
                StudentId = mark.StudentId,
                TeacherSubject = new Domain.Models.TeacherSubject
                {
                    TeacherId = mark.TeacherId,
                    SubjectId = mark.SubjectId,
                }
            };

            var res = await markService.Add(model);

            return new JsonResult("");
        }

        [HttpGet]
        public async Task<IActionResult> GetMarks()
        {
            var res = await markService.GetAll();

            return new JsonResult(res);
        }

    }
}


//public class Article
//{
//    public int GradeId { get; set; }
//    public int StudentId { get; set; }
//    public int SubjectId { get; set; }
//    public int TeacherId { get; set; }
//    public int Marks { get; set; }
//    public int TeacherSubjectId { get; set; }
//}

PracticalTest/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticalTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.2/css/jquery.dataTables.min.css">
</head>
<body style="margin-bottom:0">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">PracticalTest</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Mark" asp-action="AddMarks">Add Marks</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">

        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="https://unpkg.com/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/axios@0.2.1/dist/axios.min.js"></script>

    @*<script src="https://code.jquery.com/jquery.js"></script>*@
    <script src="https://cdn.datatables.net/1.11.2/js/jquery.dataTables.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>